# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'src\PFBridge.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      git clone https://github.com/zqu1016/IBoxsForOnoQQ.git
      ls
      Copy-Item -Path "IBoxsForOnoQQ\packages" -Destination "src\packages" -Recurse
      cd src
      ls
      cd packages
      ls 
      cd ..
      cd ..

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: '**\*.dll'
    searchFolder: 'robot'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'robot'
    ArtifactName: 'dist'
    publishLocation: 'Container'


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'release_node.md'
    ArtifactName: 'release_node'
    publishLocation: 'Container'