'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class ResourceFiles
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PFBridgeCore.ResourceFiles", GetType(ResourceFiles).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似  的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property command() As String
            Get
                Return ResourceManager.GetString("command", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 //本文件是脚本加载器，正常使用时请勿改动
        '''/*
        '''//写入最新的默认index.js(用于更新)
        ''' IO.File.WriteAllText(IO.Path.Combine(api.pluginDataPath, &quot;index_new.js&quot;), ResourceFiles.index)
        '''*/
        '''const IO = importNamespace(&apos;System.IO&apos;);//导入命名空间
        '''const FileSystem = importNamespace(&apos;Microsoft.VisualBasic.FileIO&apos;).FileSystem;
        '''const PFBridgeCore = importNamespace(&apos;PFBridgeCore&apos;)
        '''const api = PFBridgeCore.APIs.API
        '''const events = PFBridgeCore.APIs.Events
        '''const MCConnections = PFBridgeCore.ConnectionList.MCConnections
        '''//#region 加载自定义程序集(位于libs目录下)
        '''try [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property index() As String
            Get
                Return ResourceManager.GetString("index", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 const AdminQQs = [441870948, 233333]//管理员QQ号
        '''const Groups = [
        '''    {
        '''        id: 626872357,//QQ群号
        '''        ServerMsgToGroup: true,//是否转发服务器的各种消息到该群
        '''        GroupMsgToServer: true//是否将该群的消息转发到所有服务器
        '''    }
        ''']
        '''const Servers = [
        '''    {
        '''        type: &quot;websocket&quot;,
        '''        url: &quot;ws://127.0.0.1:29132/mcws&quot;,//websocket地址|如{&quot;Port&quot;: &quot;29132&quot;,&quot;EndPoint&quot;: &quot;mcws&quot;,&quot;Password&quot;: &quot;commandpassword&quot;}对应ws://127.0.0.1:29132/mcws
        '''        token: &quot;commandpassword&quot;,//websocket密匙串（用于运行命令等操作）|&quot;Password&quot;: &quot;commandpassword&quot;
        '''       [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property main() As String
            Get
                Return ResourceManager.GetString("main", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 moduleInfo.Author = &quot;littlegao233&quot;
        '''moduleInfo.Version = &quot;v0.0.1&quot;
        '''moduleInfo.Description = &quot;群内使用/list命令查询服务器在线玩家\n服务器内使用/list命令自动反馈其他服务器的在线状态&quot;
        '''
        '''
        '''const MCConnections = importNamespace(&apos;PFBridgeCore&apos;).ConnectionList.MCConnections
        '''const api = importNamespace(&apos;PFBridgeCore&apos;).APIs.API
        '''//#region &gt;&gt;&gt;&gt;&gt;-----公共方法(建议折叠)-----&gt;&gt;&gt;&gt;&gt;
        '''// /**
        '''// * 发送消息到所有已经连接并且配置开启GroupMsgToServer的MC服务器
        '''// * @param {string} message 消息内容
        '''// */
        '''//function SendBoardcastToAllServer(message) {
        '''//    MCConnections.forEach(connection  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property query() As String
            Get
                Return ResourceManager.GetString("query", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
