'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class ResourceFiles
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PFBridgeCore.ResourceFiles", GetType(ResourceFiles).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  重写当前线程的 CurrentUICulture 属性，对
        '''  使用此强类型资源类的所有资源查找执行重写。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 moduleInfo.Author = &quot;littlegao233&quot;;
        '''moduleInfo.Version = &quot;v0.0.2&quot;;
        '''moduleInfo.Description = &apos;群内使用&quot;/cmd [服务器] &lt;命令&gt;&quot;命令执行服务器命令&apos;;
        '''//简单设置：
        '''const JudgePermissionByConfig = true;
        '''//JudgePermissionByConfig：是否通过配置文件判断权限
        '''//  - true：仅有main.js配置的管理员QQ课执行
        '''//  - false：发送者为群内的管理员就能执行
        '''const events = importNamespace(&apos;PFBridgeCore&apos;).APIs.Events
        '''const api = importNamespace(&apos;PFBridgeCore&apos;).APIs.API
        '''const MCConnections = importNamespace(&apos;PFBridgeCore&apos;).ConnectionList.MCConnections
        '''function JudgePermission(e) {
        '''    i [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property command() As String
            Get
                Return ResourceManager.GetString("command", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property format() As String
            Get
                Return ResourceManager.GetString("format", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 //本文件是脚本加载器，正常使用时请勿改动
        '''/*
        '''//写入最新的默认index.js(用于更新)
        ''' IO.File.WriteAllText(IO.Path.Combine(api.pluginDataPath, &quot;index_new.js&quot;), ResourceFiles.index)
        '''*/
        '''const IO = importNamespace(&apos;System.IO&apos;);//导入命名空间
        '''const FileSystem = importNamespace(&apos;Microsoft.VisualBasic.FileIO&apos;).FileSystem;
        '''const PFBridgeCore = importNamespace(&apos;PFBridgeCore&apos;)
        '''const api = PFBridgeCore.APIs.API
        '''const events = PFBridgeCore.APIs.Events
        '''const MCConnections = PFBridgeCore.ConnectionList.MCConnections
        '''//#region 加载自定义程序集(位于libs目录下)
        '''try [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property index() As String
            Get
                Return ResourceManager.GetString("index", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 moduleInfo.Author = &quot;littlegao233&quot;
        '''moduleInfo.Version = &quot;v0.0.2&quot;
        '''moduleInfo.Description = &quot;包含配置文件的读写、\n服务器之间的同步、\n群与服务器的聊天同步、\n加入服务器的群反馈&quot;
        '''
        '''let AdminQQs = new Array()
        '''let Groups = new Array()
        '''let Servers = new Array()
        '''//#region 共享数据
        '''const engine = importNamespace(&apos;PFBridgeCore&apos;).Main.Engine
        '''engine.SetShareData(&quot;GetConfigGroups&quot;, () =&gt; { return Groups; })
        '''engine.SetShareData(&quot;GetConfigAdminQQs&quot;, () =&gt; { return AdminQQs; })
        '''//#endregion
        '''
        '''//#region &gt;&gt;&gt;&gt;&gt;-----公共方法(建议折叠)-----&gt;&gt;&gt;&gt;&gt;
        '''const ConnectionMa [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property main() As String
            Get
                Return ResourceManager.GetString("main", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 moduleInfo.Author = &quot;littlegao233&quot;
        '''moduleInfo.Version = &quot;v0.0.2&quot;
        '''moduleInfo.Description = &quot;群内使用/list命令查询服务器在线玩家\n服务器内使用/list命令自动反馈其他服务器的在线状态&quot;
        '''
        '''
        '''const MCConnections = importNamespace(&apos;PFBridgeCore&apos;).ConnectionList.MCConnections
        '''const api = importNamespace(&apos;PFBridgeCore&apos;).APIs.API
        '''//#region &gt;&gt;&gt;&gt;&gt;-----公共方法(建议折叠)-----&gt;&gt;&gt;&gt;&gt;
        '''// /**
        '''// * 发送消息到所有已经连接并且配置开启GroupMsgToServer的MC服务器
        '''// * @param {string} message 消息内容
        '''// */
        '''//function SendBoardcastToAllServer(message) {
        '''//    MCConnections.forEach(connection  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property query() As String
            Get
                Return ResourceManager.GetString("query", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 moduleInfo.Author = &quot;littlegao233&quot;
        '''moduleInfo.Version = &quot;v0.0.2&quot;
        '''moduleInfo.Description = &apos;群内管理员使用&quot;/白名单 &lt;添加|删除&gt; [服务器] &lt;玩家名&gt;&quot;操作白名单\n群内使用&quot;/白名单 查询 [服务器] &lt;玩家名&gt;查询白名单&apos;
        '''//简单设置：
        '''const JudgePermissionByConfig = true;
        '''//JudgePermissionByConfig：是否通过配置文件判断权限
        '''//  - true：仅有main.js配置的管理员QQ课执行
        '''//  - false：发送者为群内的管理员就能执行
        '''function JudgePermission(e) {
        '''    if (JudgePermissionByConfig) {
        '''        const { senderId } = e;
        '''        //根据配置文件main.js中的管理员判断权限
        '''        return GetConfigAdminQQs().some(l =&gt; l == senderId);
        '''   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Public Shared ReadOnly Property whitelist() As String
            Get
                Return ResourceManager.GetString("whitelist", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
